apiVersion: apps/v1
kind: Deployment
metadata:
  name: toko-buku-online-deployment
  namespace: toko-buku
  labels:
    app: toko-buku-online
spec:
  replicas: 3 # Jumlah replika pod yang akan dibuat
  selector:
    matchLabels:
      app: toko-buku-online
  template:
    metadata:
      labels:
        app: toko-buku-online
    spec:
      containers:
      - name: toko-buku-online-container
        image: koplomen/toko_buku_online:v1.0.0 # Gunakan versi image tertentu, bukan 'latest'
        ports:
        - containerPort: 80 # Sesuaikan jika aplikasi menggunakan port lain
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: toko-buku-secrets
              key: app-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: toko-buku-online-service
  namespace: toko-buku
  labels:
    app: toko-buku-online
spec:
  type: LoadBalancer # Bisa diubah ke ClusterIP jika hanya ingin digunakan secara internal
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: toko-buku-online

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: toko-buku-online-hpa
  namespace: toko-buku
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: toko-buku-online-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: toko-buku-secrets
  namespace: toko-buku
type: Opaque
data:
  app-key: bXlTdXBlckFwcEtleQ== # Base64-encoded secret key (contoh: "mySuperAppKey")
